## Why size of docker image matters
# The size has an impact on following
# network latency – need to transfer Docker image over the web
# storage – need to store all these bits somewhere
# service availability and elasticity – when using a Docker scheduler, like Kubernetes, Swarm, Nomad, DC/OS or other (the scheduler can move containers between hosts)
# security – do you really, I mean really need the libpng package with all its CVE vulnerabilities for your Java application?
# development agility – small Docker images == faster build time and faster deployment
